[squash rebase] player: when playback error because no connection, stop song and show loading. When connection back, start playing again
onError: finish wait to reconnect

rebase: fix

on error: simplify logic (remove toggle, just wait for connection or skip upt to two songs on error)

refactor: remove duplicate enum

player: Fixup new on-error logic

* Resurrect runaway diesel engine protection for auto skip
* Re-order if else such to show error message on auto skip
* Separate wait to reconnect on it's own

retry: if pause stop wait for reconnect

update to new string changes